node{
    stage('SCM Checkout'){
        checkout([$class: 'GitSCM', branches: [[name: '*/fullstack']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '63da01e0-fa63-4adf-bd12-433b55f48a5d', url: 'https://github.com/UpasakGanguly/FSD-SBA-FINAL-PROJECT.git']]])
    }
    stage('Maven Build'){
       withEnv(['MYTOOL_HOME=/var/jenkins_home/workspace/project_manager_jenkins_file@tmp/durable-81e77713/']) {
           sh '$MYTOOL_HOME/bin/mvn install'
          }
        sh "{mvnHome}/bin/mvn install"
        dir('/projectmanager-server') {
           sh "{mvnHome}/bin/mvn package docker build"
           }    
      }
}
