pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'JAVA-jdk'
    }
    stages {
        stage ('Build') {
            steps {
                    bat 'mvn install'
            }
        }
        stage ('Docker-Build') {
            steps {
                    bat 'cd projectmanager-server && mvn package docker:build'
            }
        }
    }
}
